### ISSUE TITLE
Transform-EaDiagramToVisio.ps1 - Assign Name of EA Element to Visio Shape on creation

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.EnterpriseArchitect.Scripts#11]
Assign Name of EA element to corresponding Visio shape on creation.

**TODOs**
* [x] Search for EA element in EA project by `ElementID` of EA diagram object
* [x] Get Name from EA element
* [x] Pass Name of EA element to Visio shape on creation
