### ISSUE TITLE
Create Module biz.dfch.PS.EnterpriseArchitect

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.EnterpriseArchitect.Scripts#3]
**TODOs**
* [ ] Create module `biz.dfch.PS.Visio`
* [ ] Remove parameter `VisioScriptsDirectory` from `Transform-EaDiagramToVisio.ps1`
* [ ] Add `biz.dfch.PS.Visio` module requirement to `Transform-EaDiagramToVisio.ps1`
* [ ] Remove dot sourcing code from BEGIN block of `Transform-EaDiagramToVisio.ps1`
* [ ] Create Module `biz.dfch.PS.EnterpriseArchitect`
* [ ] Set `DefaultCommandPrefix` to `Ea`
